# Site settings
title: Matt Henry
email: blog@matthenry.fastmail.fm
description: > # this means to ignore newlines until "baseurl:"
  I'm a public defender in Southeastern Massachusetts, and I blog about apple things,
  workflows, maybe law stuff, and whatever else I feel like.
  Views are mine alone. This is not legal advice and I am not your lawyer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://heymatthenry.github.io" # the base hostname & protocol for your site
twitter_username: heymatthenry
github_username:  heymatthenry

# Build settings
markdown: kramdown
